<Project Sdk="Godot.NET.Sdk/4.8.0-dev">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <Nullable>enable</Nullable>
    <ImplicitUsings>false</ImplicitUsings>
    <RootNamespace>FPSGame</RootNamespace>
    <AssemblyName>FPSGame</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
      <_Parameter1>BuildUtc</_Parameter1>
      <_Parameter2>$([System.DateTime]::UtcNow.ToString("O"))</_Parameter2>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
